[package]
name = "sdl-rust"
version = "0.1.0"
edition = "2021"
authors = ["Minh Vu <minhd_vu@yahoo.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.0"